# Practice Lab: Selecting data in a Dataframe
## Author/Executor: LiR
### Date:19-12-2025

In [2]:
# let us import the Pandas Library
import pandas as pd

In [3]:
#Define a dictionary 'x'

x = {'Name': ['Rose','John', 'Jane', 'Mary'], 'ID': [1, 2, 3, 4], 'Department': ['Architect Group', 'Software Group', 'Design Team', 'Infrastructure'], 
      'Salary':[100000, 80000, 50000, 60000]}

#casting the dictionary to a DataFrame
df = pd.DataFrame(x)

#display the result df
df

   Name  ID       Department  Salary
0  Rose   1  Architect Group  100000
1  John   2   Software Group   80000
2  Jane   3      Design Team   50000
3  Mary   4   Infrastructure   60000

In [4]:
#Retrieving the "ID" column and assigning it to a variable x
x = df[['ID']]
x

   ID
0   1
1   2
2   3
3   4

In [5]:
#check the type of x
type(x)

pandas.core.frame.DataFrame

In [6]:
#Retrieving the Department, Salary and ID columns and assigning it to a variable z

z = df[['Department','Salary','ID']]
z

        Department  Salary  ID
0  Architect Group  100000   1
1   Software Group   80000   2
2      Design Team   50000   3
3   Infrastructure   60000   4

In [11]:
#Problem 1: Create a dataframe to display the result as below:
myDictX = {'Student':['David', 'Samuel', 'Terry', 'Evan'],
     'Age':['27', '24', '22', '32'],
     'Country':['UK', 'Canada', 'China', 'USA'],
     'Course':['Python','Data Structures','Machine Learning','Web Development'],
     'Marks':['85','72','89','76']}
df_new = pd.DataFrame(myDictX)
df_new

  Student Age Country            Course Marks
0   David  27      UK            Python    85
1  Samuel  24  Canada   Data Structures    72
2   Terry  22   China  Machine Learning    89
3    Evan  32     USA   Web Development    76

In [18]:
#Problem 2: Retrieve the Marks column and assign it to a variable b
b = df_new[['Marks']]
b

  Marks
0    85
1    72
2    89
3    76

In [20]:
#Problem 3: Retrieve the Country and Course columns and assign it to a variable c
c = df_new[['Country','Course']]
c

  Country            Course
0      UK            Python
1  Canada   Data Structures
2   China  Machine Learning
3     USA   Web Development

In [21]:
# Get the Student column as a series Object
x = df_new['Student']
x

0     David
1    Samuel
2     Terry
3      Evan
Name: Student, dtype: object

In [22]:
#check the type of x
type(x)

pandas.core.series.Series

In [24]:
#Exercise 2: loc() and iloc() functions
#loc[row_label, column_label]
#iloc[row_index, column_index]

# Access the value on the first row and the first column
print(df.iloc[0, 0])
# Access the value on the first row and the third column
print(df.iloc[0,2])
# Access the column using the name
print(df.loc[0, 'Salary'])

Rose
Architect Group
100000

In [31]:
df2=df
df2=df2.set_index("Name")
#To display the first 5 rows of new dataframe
print(df2.head())
#Now, let us access the column using the name
print("-------------------------- \n ['Jane', 'Salary'] ->",df2.loc['Jane', 'Salary'])

      ID       Department  Salary
Name
Rose   1  Architect Group  100000
John   2   Software Group   80000
Jane   3      Design Team   50000
Mary   4   Infrastructure   60000
--------------------------
 ['Jane', 'Salary'] -> 50000

In [34]:
#Use the loc() function,to get the Department of Jane in the newly created dataframe df2.
print("['Jane', 'Department'] ->",df2.loc['Jane', 'Department'])

['Jane', 'Department'] -> Design Team

In [39]:
#Use the iloc() function to get the Salary of Mary in the newly created dataframe df2.
print("['Mary', 'Salary'] ->",df2.iloc[3, 2])

['Mary', 'Salary'] -> 60000

In [46]:
#Exercise 3: Slicing
# let us do the slicing using old dataframe df
print(df)
print(df.iloc[0:2, 0:3])

   Name  ID       Department  Salary
0  Rose   1  Architect Group  100000
1  John   2   Software Group   80000
2  Jane   3      Design Team   50000
3  Mary   4   Infrastructure   60000
   Name  ID       Department
0  Rose   1  Architect Group
1  John   2   Software Group

In [45]:
#let us do the slicing using loc() function on old dataframe df where index column is having labels as 0,1,2
print(df)
print(10* '--')
print(df.loc[0:2,'ID':'Department'])

   Name  ID       Department  Salary
0  Rose   1  Architect Group  100000
1  John   2   Software Group   80000
2  Jane   3      Design Team   50000
3  Mary   4   Infrastructure   60000
--------------------
   ID       Department
0   1  Architect Group
1   2   Software Group
2   3      Design Team

In [43]:
#let us do the slicing using loc() function on new dataframe df2 where index column is Name having labels: Rose, John and Jane
df2.loc['Rose':'Jane', 'ID':'Department']

      ID       Department
Name
Rose   1  Architect Group
John   2   Software Group
Jane   3      Design Team

In [53]:
#using loc() function, do slicing on old dataframe df to retrieve the Name, ID and department of index column having labels as 2,3
print(df)
df.loc[2:3,'Name':'Department']

   Name  ID       Department  Salary
0  Rose   1  Architect Group  100000
1  John   2   Software Group   80000
2  Jane   3      Design Team   50000
3  Mary   4   Infrastructure   60000

   Name  ID      Department
2  Jane   3     Design Team
3  Mary   4  Infrastructure

In [67]:
#print(df.loc[3,'Name'])
print(df.iloc[3,0])
print(df)
print(df.loc[2:3,'Name'])

Mary
   Name  ID       Department  Salary
0  Rose   1  Architect Group  100000
1  John   2   Software Group   80000
2  Jane   3      Design Team   50000
3  Mary   4   Infrastructure   60000
2    Jane
3    Mary
Name: Name, dtype: object