###    Practice Project: GDP Data Extraction
####   Author  : LiR
#####  Date    : 31-12-2025
######  extract data from a website using webscraping and request APIs process it using Pandas and Numpy libraries.

#### Project Scenario:
##### An international firm that is looking to expand its business in different countries across the world has recruited you. You have been hired as a junior Data Engineer and are tasked with creating a script that can extract the list of the top 10 largest economies of the world in descending order of their GDPs in Billion USD (rounded to 2 decimal places), as logged by the International Monetary Fund (IMF).

###### The required data seems to be available on the URL mentioned below:
###### URL: https://web.archive.org/web/20230902185326/https://en.wikipedia.org/wiki/List_of_countries_by_GDP_%28nominal%29

In [215]:
#Install required packages
!pip install pandas numpy 
!pip install lxml

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\dev_soft\anaconda3_2023\lib\site-packages (2.3.3)
Requirement already satisfied: numpy in c:\users\rusla\appdata\roaming\python\python311\site-packages (2.4.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\dev_soft\anaconda3_2023\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\dev_soft\anaconda3_2023\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\dev_soft\anaconda3_2023\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\dev_soft\anaconda3_2023\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: lxml in c:\dev_soft\anaconda3_2023\lib\site-packages (5.3.0)

In [216]:
import numpy as np
import pandas as pd

# You can also use this section to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass

import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')

####    Exercises

In [217]:
#Exercise 1
#Extract the required GDP data from the given URL using Web Scraping.
import requests
import pandas as pd


url = "https://web.archive.org/web/20230902185326/https://en.wikipedia.org/wiki/List_of_countries_by_GDP_%28nominal%29"
#url = 'https://en.wikipedia.org/wiki/List_of_largest_banks'
#url = 'https://en.wikipedia.org/wiki/List_of_countries_by_GDP_%28nominal%29'
#local_file = "Largest_economies.csv"

response = requests.get(url)

if response.status_code == 200:
    #with open(local_file, "wb") as f:
    #    f.write(response.content)
    tables = pd.read_html(response.text)
else:
    raise Exception(f"Download failed: {response.status_code}")

#df = pd.read_csv(local_file, header=None)
#print('len(tables) -> ',len(tables))
df1 = pd.DataFrame(tables[1])
#print(df1.head())
df2 = tables[2] # -> with Estimate 
#print('tables[2].head()-----------\n',tables[2].head())
df3 = tables[3]
df2.columns
#df2 = df2.sort_values(
#    by=[
#        ('IMF[1][13]', 'Estimate'),
#        ('World Bank[14]', 'Estimate'),
#        ('United Nations[15]', 'Estimate')
#    ],
#    ascending=[True, True]
#)
df2

    Country/Territory UN region IMF[1][13]            World Bank[14]  \
    Country/Territory UN region   Estimate       Year       Estimate
0               World         —  105568776       2023      100562011
1       United States  Americas   26854599       2023       25462700
2               China      Asia   19373586  [n 1]2023       17963171
3               Japan      Asia    4409738       2023        4231141
4             Germany    Europe    4308854       2023        4072192
..                ...       ...        ...        ...            ...
209          Anguilla  Americas          —          —              —
210          Kiribati   Oceania        248       2023            223
211             Nauru   Oceania        151       2023            151
212        Montserrat  Americas          —          —              —
213            Tuvalu   Oceania         65       2023             60

               United Nations[15]
          Year           Estimate       Year
0         2022           96698005       2021
1         2022           23315081       2021
2    [n 3]2022           17734131  [n 1]2021
3         2022            4940878       2021
4         2022            4259935       2021
..         ...                ...        ...
209          —                303       2021
210       2022                227       2021
211       2022                155       2021
212          —                 72       2021
213       2022                 60       2021

[214 rows x 8 columns]

In [218]:
#rename Column
df2.columns = range(df2.shape[1]) #['Col1','Col2'] # or to int [1,2] or range(df3.shape[1])
df2.columns

RangeIndex(start=0, stop=8, step=1)

In [219]:
# Retain columns with index 0 and 2 (name of country and value of GDP quoted by IMF)
df2 = df2[[0,2]]
df2

                 0          2
0            World  105568776
1    United States   26854599
2            China   19373586
3            Japan    4409738
4          Germany    4308854
..             ...        ...
209       Anguilla          —
210       Kiribati        248
211          Nauru        151
212     Montserrat          —
213         Tuvalu         65

[214 rows x 2 columns]

In [220]:
# Retain the Rows with index 1 to 10, indicating the top 10 economies of the world.
df2 = df2.iloc[1:11,:]
df2

                 0         2
1    United States  26854599
2            China  19373586
3            Japan   4409738
4          Germany   4308854
5            India   3736882
6   United Kingdom   3158938
7           France   2923489
8            Italy   2169745
9           Canada   2089672
10          Brazil   2081235

In [221]:
# Assign column names as "Country" and "GDP (Million USD)"
df2.columns = ['Country','GDP (Million USD)']
df2

           Country GDP (Million USD)
1    United States          26854599
2            China          19373586
3            Japan           4409738
4          Germany           4308854
5            India           3736882
6   United Kingdom           3158938
7           France           2923489
8            Italy           2169745
9           Canada           2089672
10          Brazil           2081235

####    Exercise 2

In [222]:
# Change the data type of the 'GDP (Million USD)' column to integer. Use astype() method.
#import numpy as np
df2['GDP (Million USD)'] = df2['GDP (Million USD)'].astype(int)
#df2 = df2.loc[1,2]
#df2

In [223]:
# Convert the GDP value in Million USD to Billion USD
df2[['GDP (Million USD)']] = df2[['GDP (Million USD)']]/1000
df2

           Country  GDP (Million USD)
1    United States          26854.599
2            China          19373.586
3            Japan           4409.738
4          Germany           4308.854
5            India           3736.882
6   United Kingdom           3158.938
7           France           2923.489
8            Italy           2169.745
9           Canada           2089.672
10          Brazil           2081.235

In [224]:
# Use numpy.round() method to round the value to 2 decimal places.
import numpy as np
df2[['GDP (Million USD)']] = np.round(df2[['GDP (Million USD)']], 2)
df2

           Country  GDP (Million USD)
1    United States           26854.60
2            China           19373.59
3            Japan            4409.74
4          Germany            4308.85
5            India            3736.88
6   United Kingdom            3158.94
7           France            2923.49
8            Italy            2169.74
9           Canada            2089.67
10          Brazil            2081.24

In [225]:
# Rename the column header from 'GDP (Million USD)' to 'GDP (Billion USD)'
df2.rename(columns = {'GDP (Million USD)' : 'GDP (Billion USD)'})

           Country  GDP (Billion USD)
1    United States           26854.60
2            China           19373.59
3            Japan            4409.74
4          Germany            4308.85
5            India            3736.88
6   United Kingdom            3158.94
7           France            2923.49
8            Italy            2169.74
9           Canada            2089.67
10          Brazil            2081.24

In [226]:
#print(df2)
print(type(df2))      # должен быть pandas.DataFrame
print(df2.shape)    
#print(df2.head())
print(df2.columns)

<class 'pandas.core.frame.DataFrame'>
(10, 2)
Index(['Country', 'GDP (Million USD)'], dtype='object')

####    Exercise 3

In [227]:
#Load the DataFrame to the CSV file named "Largest_economies.csv"
local_file = "Largest_economies.csv"
df2.to_csv('./' + local_file,sep=',', index=False,encoding='utf-8-sig') # default sep=','

In [228]:
#упрощаем доступ до первого уровня
#df2.columns = df2.columns.get_level_values(0)
#df2.columns